# Site settings
title: SimpleCV
description: > # SimpleCV is an open source framework for building computer vision
  applications. With it, you get access to several high-powered computer vision
  libraries such as OpenCV – without having to first learn about bit depths, file
  formats, color spaces, buffer management, eigenvalues, or matrix versus bitmap
  storage. This is computer vision made easy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simplecv.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
